# Generated by Django 4.2.9 on 2024-01-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0005_rename_start_date_holiday_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='free_slots',
            new_name='freeSlots',
        ),
    ]
