# Generated by Django 4.2.9 on 2024-01-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0007_alter_holiday_price_alter_holiday_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='contact_name',
            new_name='contactName',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
