# Generated by Django 4.2.9 on 2024-01-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('free_slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('imageURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.holiday')),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.location'),
        ),
    ]
