# Generated by Django 4.2.9 on 2024-01-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='imageURL',
        ),
    ]
