# Generated by Django 4.2.9 on 2024-01-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_alter_holiday_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
